In [8]:
from array import *

# create a 2d array 

data = [[11,22,33],[44,55,66],[77,88,99]]

print(data[1][2])

# print the 2d array
# print index of 2d array
for i in range(0,3):
    for j in range(0,3):
        print(i,j," ",end=' ')
    print()

# print the item from array   


for i in range(0,3):
    for j in range(0,3):
        print(data[i][j],end=' ')
    print()    

66
0 0   0 1   0 2   
1 0   1 1   1 2   
2 0   2 1   2 2   
11 22 33 
44 55 66 
77 88 99 


In [9]:
# Modifying Elements in the 2D array
# change the value of 55 to 100

data[1][1] = 100

for i in range(0,3):
    for j in range(0,3):
        print(data[i][j],end=' ')
    print()

11 22 33 
44 100 66 
77 88 99 


In [10]:
# Adding Elements to the 2D array
# add a new row to the 2D array

data.append([10,20,30])

for i in range(0,4):
    for j in range(0,3):
        print(data[i][j],end=' ')
    print()

11 22 33 
44 100 66 
77 88 99 
10 20 30 


In [11]:
# using numpy to create 2d array

import numpy as np

data = np.array([[11,22,33],[44,55,66],[77,88,99]])

print(data)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [12]:
# numpy.zeros() function to create a 2D array with all elements as 0

data = np.zeros((3,3))
print(data)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# numpy.ones() function to create a 2D array with all elements as 1

data = np.ones((3,3))
print(data)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# numpy.arange
# numpy.arange() function to create a 2D array with a sequence of numbers

data = np.arange(0,16).reshape(4,4)
print(data)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
