In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

data1 = np.array([23,56,45,78,89])
print(data1)

# check type 
print(type(data1))

# check shape
print(data1.shape)

# check size
print(data1.size)

# check dime
print(data1.ndim)

[23 56 45 78 89]
<class 'numpy.ndarray'>
(5,)
5
1


In [12]:
# 2nd array
data1 = np.array([[23,56,45],[23,56,45]])
print(data1)

# check type 
print(type(data1))

# check shape
print(data1.shape)

# check size
print(data1.size)

# check dime
print(data1.ndim)

[[23 56 45]
 [23 56 45]]
<class 'numpy.ndarray'>
(2, 3)
6
2


In [13]:
for i in data1:
    for n in i:
        print(n,end=" ")
    print() 

23 56 45 
23 56 45 


In [16]:
print(data1[0,1])

56


In [8]:
# 3nd array
data1 = np.array([[[23,56,45],[23,56,45]],[[23,56,45],[23,56,45]]])
print(data1)

# check type 
print(type(data1))

# check shape
print(data1.shape)

# check size
print(data1.size)

# check dime
print(data1.ndim)

[[[23 56 45]
  [23 56 45]]

 [[23 56 45]
  [23 56 45]]]
<class 'numpy.ndarray'>
(2, 2, 3)
12
3


In [9]:
# 4nd array
data1 = np.array([[[[23,56,45],[23,56,45]],[[23,56,45],[23,56,45]]],[[[23,56,45],[23,56,45]],[[23,56,45],[23,56,45]]]])
print(data1)

# check type 
print(type(data1))

# check shape
print(data1.shape)

# check size
print(data1.size)

# check dime
print(data1.ndim)

[[[[23 56 45]
   [23 56 45]]

  [[23 56 45]
   [23 56 45]]]


 [[[23 56 45]
   [23 56 45]]

  [[23 56 45]
   [23 56 45]]]]
<class 'numpy.ndarray'>
(2, 2, 2, 3)
24
4
