In [3]:
from array import *
data = [[11,12,13,14],[15,16,17],[18,19,20,21],[22,23,24,25]]

print(data)
# access item from array 
print(data[0])
# access item from array 
print(data[1][2])

[[11, 12, 13, 14], [15, 16, 17], [18, 19, 20, 21], [22, 23, 24, 25]]
[11, 12, 13, 14]
17


In [4]:
# print complete array 

for i in data:
    for n in i:
        print(n,end=" ")
    print()    

11 12 13 14 
15 16 17 
18 19 20 21 
22 23 24 25 


In [6]:
# Create a 2D array using Lists of lists
two_d_array=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
# accessing elements in the 2D array
print(two_d_array[0][0])
print(two_d_array[1][2])

# Modifying Elements in the 2D array 
two_d_array[2][1] = 10
print(two_d_array)

1
6
[[1, 2, 3], [4, 5, 6], [7, 10, 9]]


In [7]:
# you can create a 2D array using NumPy:
import numpy as np

# Create a 2D array using NumPy
two_d_array_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Accessing elements in the 2D array
print(two_d_array_np[0, 0])  # Output: 1
print(two_d_array_np[1, 2])  # Output: 6

# Modifying elements in the 2D array
two_d_array_np[2, 1] = 10
print(two_d_array_np)
# Output:
# [[ 1  2  3]
#  [ 4  5  6]
#  [ 7 10  9]]


1
6
[[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]
